### ISSUE TITLE
record_ert fails trying to copy roofline_config_template

### ISSUE THREAD

**Issue by derekbruening** [arm-hpc/roofline#1]
The roofline.py script assumes a file named `roofline_config_template` exists in `ert/Empirical_Roofline_Tool-1.1.0` but it does not:
```
$ git clone https://github.com/arm-hpc/roofline.git
$ cd roofline/
$ make
$ ./roofline.py record_ert --precision FP64
Running ERT for gathering a roofline for precision FP64
Traceback (most recent call last):
  File "./roofline.py", line 694, in <module>
    sys.exit(main())
  File "./roofline.py", line 690, in main
    args.func(args)
  File "./roofline.py", line 508, in record_ert
    copyfile("roofline_config_template", "roofline_config")
  File "/usr/lib/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'roofline_config_template'
```

Looking at the git history of the ert code: I don't see that any file by that name ever existed?
Trying to copy an existing file like `ert/Empirical_Roofline_Tool-1.1.0/Config/config.babbage.nersc.gov.01`: these have specific MPI or OpenMP specifications with specific compiler flags.  Does the user need to hand-construct a file listing the right flags to get, say, gcc to generate the right AVX-512 or AVX-2 instructions for the underlying processor?

**Comment by nanxia1985** [comment]
I got the same question...
